### ISSUE TITLE
A small advise

### ISSUE THREAD

**Issue by OshinoMoumou** [goulu/Goulib#13]
Hello!
I noticed that the 'subdict' method in file Goulib/itertools2.py quoted a stack overflow answer, where a comment proposed that dict((k,bigdict.get(k,defaultVal) for k in wanted_keys) is better than dict([(i, d[i]) for i in keys if i in d]). (the url is [here](https://stackoverflow.com/questions/5352546/extract-subset-of-key-value-pairs-from-python-dictionary-object/5352649#comment87265572_5352649) ) The original answer adopted it and modified the code. 
I think it may help improve your code. 
Have a nice day!

**Comment by goulu** [comment]
thanks for your suggestion, and sorry for the delay in examining it. Actually  there is a difference in behaviour :

`dict((k,bigdict.get(k,defaultVal) for k in wanted_keys)  ` sets d[k] to defaultVal if bigdict doesn't contain  key k 

while the solution I implemented

`dict([(i, d[i]) for i in keys if i in d])` doesn't create a d[i] element at all in this case

Since I'm using this function to select subsets of **kwargs passed to some functions that precisely do not accept extra elements in their params, I prefer to keep the existing code
